### ISSUE TITLE
"active sources" should count only sources not in error state

### ISSUE THREAD

**Issue by ZeroChaos-** [elkentaro/KismetMobileDashboard#1]
Great ui btw, love it. only one issue so far... if everything is working fine and I'm sniffing BT and wifi and, for example, yank my wifi card out, the ui still shows 2 active sources.

Now that is kinda true, because kismet still knows the wifi card is a source, and if I plug it back in kismet will grab it.  But imho either the count should drop or the number should turn red or some other indication that things aren't okay.

**Comment by elkentaro** [comment]
Good point. Changed the number of "Active Sources" only to list the real "running" sources instead of  the sources listed in the kismet configuration file.

**Comment by elkentaro** [comment]
The kismet alert system will trigger an alert saying there is an issue with an interface that is listed but not "active" , not sure if this is enough? Should I also list how many or which interface is having a problem?

**Comment by ZeroChaos-** [comment]
I have no business in ui/ux design but something should tell me it is broke.  Having the number in red when a source is broken would be great.  I think having a whole extra element for broken sources (which likely does not happen much) would be excessive.  The alert system is honestly not enough, because the purpose of a dashboard is to not have to look at such things.  I was mostly using your ui for "is it still working" from my phone, and clicking around kinda sucks (tiny element for alerts plus phone screen equals annoying)

**Comment by ZeroChaos-** [comment]
It might help to have a generic messages section and show things like which interface is broke (or other alerts which may he of interest), but then again, that may ruin the clean simple design you have now :-)

**Comment by elkentaro** [comment]
Ok. Added the changing of colors.  Now if there is an interface having issues the "Active Sources" will turn to Red once its resolved it should turn back to black. Let me see if I can add a "message section" somewhere in the UI.
