### ISSUE TITLE
Missing name= in plugin manifest

### ISSUE THREAD

**Issue by ZeroChaos-** [elkentaro/KismetMobileDashboard#3]
While starting kismet
```
ERROR: Error reading config file '/usr/lib64/kismet//mobiledashboard/manife
       st.conf': 2
ERROR: Missing 'name=' in plugin manifest '/usr/lib64/kismet//mobiledashboa
       rd/manifest.conf', cannot load plugin
```

**Comment by elkentaro** [comment]
hm.. I can't replicate this error....
i get :
root@pocketkali:~/kismet/KismetMobileDashboard# cat test.txt  | grep mobile
INFO: Plugin 'mobiledashboard' loaded...

**Comment by ZeroChaos-** [comment]
my bad, I was out of date.  New git tag please?
